### ISSUE TITLE
Numberpad support?

### ISSUE THREAD

**Issue by KieranDevvs** [rmaes4/decimal-prices#1]
@rmaes4 

Decimal places cannot be added when using a number pad.

DecimalPricesKeyListener.java:80
```
} else if(e.getKeyCode() == KeyEvent.VK_PERIOD && isQuantityInput()) {
```

Should also include VK_DECIMAL
https://docs.oracle.com/javase/7/docs/api/java/awt/event/KeyEvent.html#VK_DECIMAL

i.e
```
    @Override
    public void keyPressed(KeyEvent e) {
        int keyCode = e.getKeyCode();

        if(keyCode == KeyEvent.VK_ENTER && isQuantityInput()) {
            // intercept quantity entry before it is sent to the server
            convertQuantity();
        } else if(isKeyDecimal(keyCode) && isQuantityInput()) {
            // allow typing of decimal in quantity input field which is otherwise not possible to do
            addDecimalToInputText();
        }
    }

    private bool isKeyDecimal(int keyCode) {
        switch(keyCode) {
            case KeyEvent.VK_PERIOD:
            case KeyEvent.VK_DECIMAL:
                return true;
            default:
                return false;
        }
    }
```

**Comment by rmaes4** [comment]
Thank you for bringing this to my attention! I'll be honest I don't really use the numpad so I guess this slipped my mind but I will correct this.

**Comment by SandroVA** [comment]
Any updates on this? It's pretty annoying not being able to use numpad.

**Comment by rmaes4** [comment]
@KieranDevvs @SandroVA Apologies for the radio silence. I have been very busy due to the holidays. I have gone ahead and updated the plugin. We now have to wait for the runelite team to accept the update before you can use it. You can see the status of my pull request here: https://github.com/runelite/plugin-hub/pull/882

Happy holidays!
