### ISSUE TITLE
Update to RL 1.8.25

### ISSUE THREAD

**Issue by YvesW** [rmaes4/decimal-prices#2]
Your plugin failed to build with the 1.8.25 changes. I haven't looked into it too closely, but if I remember correctly, getVarcIntValue should be used instead of getVar. The SetVar methods also changed IIRC. You can probably check https://github.com/runelite/runelite/commit/87b41de60e8e8973b15ff95d4ca873b16b28c354 to find the changes.
Would be lovely if you could update it; thanks in advance!

**Comment by rmaes4** [comment]
@YvesW Thank you for bringing this to my attention. I have been taking a break from this game ever since I maxed. I was not aware that this plugin broke. I will try to fix this plugin this weekend as I should have some spare time.

**Comment by YvesW** [comment]
Thank you very much, that'd be awesome!
I also lately had the problem that I'd get two dots ("..") while only entering one (i.e. the result would be "6..5k" while I only entered "6.5k"). So if you're going through your code and notice something that could cause that, then you know it might happen while playing. If you don't notice anything, I'll try test ingame once the plugin can be build and report back!

**Comment by rmaes4** [comment]
@YvesW I am fixing the plugin now. I cannot seem to reproduce the double decimal issue. Could you please include specific information as to how that issue occurs?

**Comment by rmaes4** [comment]
@YvesW I have submitted a PR to Runelite for the updated plugin here: https://github.com/runelite/plugin-hub/pull/2955

In addition to fixing the plugin I have also altered it to prevent entering more than one decimal. This should prevent the issue you were describing.

**Comment by YvesW** [comment]
@rmaes4 My apologies, I didn't see your responses earlier.
Sadly I didn't check for example my client.log or any other logs when it happened, so I don't think I have too much more info.
I'm using the US QWERTY international keyboard layout and while I was trying to enter the decimal prices, it would oddly enough always duplicate the dot. I'm not using the numpad and I'm able to enter single dots perfectly fine in other programs and in other places in the game. E.g. typing "1.2k" in public chat is no problem, but while setting the price, it would always result in "1..2k".

If I remember correctly, a singular backspace would also delete both dots, which made it basically impossible for me to enter decimal prices. However, I'm not entirely sure anymore about the backspace part, so take that with a grain of salt.

I currently can't test it since the plugin is disabled in the hub, although I could load your plugin during the weekend via IntelliJ if you'd like me to.

Very much looking forward to enabling the plugin again; thank you for your work! If I find any weird bugs, I'll report it again.

**Comment by rmaes4** [comment]
@YvesW 
Once the Runelite team makes the new version available, please test it and report back. I have modified the code to never allow more than one decimal for the price entry (I could not think of any reason why someone would need more than one). Hopefully this will fix the issue you have described!

**Comment by YvesW** [comment]
@rmaes4 I just noticed that NFC has merged the PR. Works great, thank you very much! A couple of my clanmates were already complaining that they were missing your plugin, so I'd like to thank you from them as well!

While testing I noticed that e.g. "6.k" (no decimals) and "1.234" (no k or m) results in setting it to 1. However, I'd argue that's a feature and not a bug, since those have to be typos by the user.

So with that, I'll close the issue!

**Comment by rmaes4** [comment]
@YvesW Thank you for confirming that the plugin works. I'll admit that 6.k is an edge case I had not considered. At this point I have had no complaints or issues related to that scenario so I am inclined to leave it alone. Cheers and happy scaping!
