### ISSUE TITLE
32.3m becomes 32,299,999

### ISSUE THREAD

**Issue by Zarthus** [rmaes4/decimal-prices#3]
![image](https://user-images.githubusercontent.com/3660408/223543611-b3618814-7d28-4447-8080-d89ff697d3e7.png)
![image](https://user-images.githubusercontent.com/3660408/223543659-53e44cfe-32ed-4a99-a821-2dc4c25e0258.png)

https://ideone.com/9dOsOv

https://github.com/rmaes4/decimal-prices/blob/4773c94ec3afb020ca9ffa4efa5ac16462f1b11c/src/main/java/com/decimalprices/DecimalPricesKeyListener.java#L58-L61

**Comment by rmaes4** [comment]
Thank you for bringing this issue to my attention @Zarthus 

I am wondering if this is the best solution. As we are working with what is essentially money (albeit virtual), it seems that precision is absolutely key. Perhaps it would make more sense to use BigDecimal instead? I think some more exploration is required on my part.

**Comment by Zarthus** [comment]
@rmaes4 I had the same consideration, more people would be upset if 1.3b became 1.31b or something like that I guess :) 

It's a very minor glitch all things considered, but yeah - rounding with floating points in general would be considered a suboptimal solution in general. (the current solution discards the floating point entirely, and I'm not aware of any floating maths precision error where the number would be higher; but it could exist)

**Comment by rmaes4** [comment]
@Zarthus I will take a look this weekend and let you know my findings. Thanks again.

**Comment by rmaes4** [comment]
@Zarthus I have gone ahead and submitted an update that should solve this issue. You can see it here: https://github.com/runelite/plugin-hub/pull/4041

Thank you again for bringing this to my attention. I will mark this as closed. Please let me know if you find any other issues.
