### ISSUE TITLE
no longer working

### ISSUE THREAD

**Issue by Orimazer** [rmaes4/decimal-prices#5]
the plugin doesn't seem to be working. it was after the update yesterday (even after a full runelite reload), but when i loaded runelite today it has stopped working.

**Comment by rmaes4** [comment]
> the plugin doesn't seem to be working. it was after the update yesterday (even after a full runelite reload), but when i loaded runelite today it has stopped working.

Thank you for bringing this to my attention. I had no idea this stopped working. Looking in to it

**Comment by rmaes4** [comment]
> the plugin doesn't seem to be working. it was after the update yesterday (even after a full runelite reload), but when i loaded runelite today it has stopped working.

I have submitted a fixed version to the RuneLite team. Once they approve it, you should be able to try it out. See here: https://github.com/runelite/plugin-hub/pull/6656

Thanks!

**Comment by Orimazer** [comment]
thank you, that seems to be working perfectly again!

**Comment by rmaes4** [comment]
> thank you, that seems to be working perfectly again!

Glad to hear it! Happy scaping
